name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install dependencies (Python <3.12)
      if: matrix.python-version < '3.12'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test_requirements_landfire.txt
    - name: Install dependencies (Python 3.12+)
      if: matrix.python-version >= '3.12'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test_requirements.txt
    - name: Run pytest (Python <3.12)
      if: matrix.python-version < '3.12'
      env:
        TEST_ENV: local
      run: |
        pytest
    - name: Run pytest (Python 3.12+)
      if: matrix.python-version >= '3.12'
      env:
        TEST_ENV: local
      run: |
        pytest --ignore=tests/test_landfire_module.py
